# List packages you want pre-built for armv7l
# Add new packages here and the workflow will build them

[[package]]
name = "rpds-py"
version = "0.30.0"

[[package]]
name = "pillow"
version = "12.0.0"

[[package]]
name = "pyyaml"
version = "6.0.3"

# Add more packages as needed:
# [[package]]
# name = "cryptography"
# version = "41.0.7"
